Repository compucorp/uk.co.compucorp.manageletterheads, pull requests merged in 2020-10, with the labels that each got.

#3 CATL-1791: Add letterheads list page
  CRM/ManageLetterheads/Page/LetterheadsListPage.php
  templates/CRM/ManageLetterheads/Page/LetterheadsListPage.tpl
  xml/Menu/manageletterheads.xml
Labels: enhancement

#4 CATL-1824: Letterhead form
  CRM/ManageLetterheads/Form/LetterheadForm.php
  templates/CRM/ManageLetterheads/Form/LetterheadForm.tpl
  templates/CRM/ManageLetterheads/Page/LetterheadsListPage.tpl
  xml/Menu/manageletterheads.xml
Labels: enhancement

#6 CATL-1792: Row Actions
  .github/workflows/unit-test.yml
  .gitignore
  .nvmrc
  CRM/ManageLetterheads/Page/LetterheadsListPage.php
  gulp-tasks/karma-unit-test.js
  gulpfile.js
  js/row-actions.js
  package-lock.json
  package.json
  templates/CRM/ManageLetterheads/Page/LetterheadsListPage.tpl
  tests/js/helpers/block-jquery-on-ready.js
  tests/js/helpers/civicrm-api-spy.js
  tests/js/helpers/crm-status-spy.js
  tests/js/helpers/window-location-spy.js
  tests/js/karma.conf.js
  tests/js/specs/row-actions.spec.js
Labels: enhancement

#7 CATL-1794: Edit letterheads
  CRM/ManageLetterheads/Page/LetterheadsListPage.php
Labels: enhancement

#8 CATL-1795: Delete letterhead
  js/row-actions.js
  tests/js/helpers/civicrm-api-spy.js
  tests/js/helpers/crm-confirm-spy.js
  tests/js/helpers/crm-refresh-parent-spy.js
  tests/js/helpers/crm-status-spy.js
  tests/js/helpers/window-location-spy.js
  tests/js/karma.conf.js
  tests/js/specs/row-actions.spec.js
Labels: enhancement

#9 CATL-1796: Letterheads Menu Link
  CRM/ManageLetterheads/Setup/CreateNavigationItem.php
  CRM/ManageLetterheads/Uninstall/DeleteNavigationItem.php
  CRM/ManageLetterheads/Upgrader.php
Labels: enhancement

#12 CATL-1894: Fix create message
  CRM/ManageLetterheads/Form/LetterheadForm.php
Labels: bug

#13 CATL-1795: Fix API Permissions
  CRM/ManageLetterheads/Hook/AlterAPIPermissions/AddLetterheadPermissions.php
  manageletterheads.php
Labels: bug

#11 CATL-1775: Letterheads
  .github/workflows/unit-test.yml
  .gitignore
  .nvmrc
  CRM/ManageLetterheads/Form/LetterheadForm.php
  CRM/ManageLetterheads/Hook/AlterAPIPermissions/AddLetterheadPermissions.php
  CRM/ManageLetterheads/Hook/BuildForm/AddLetterheadDropdown.php
  CRM/ManageLetterheads/Page/LetterheadsListPage.php
  CRM/ManageLetterheads/Setup/CreateNavigationItem.php
  CRM/ManageLetterheads/Uninstall/DeleteNavigationItem.php
  CRM/ManageLetterheads/Upgrader.php
  gulp-tasks/karma-unit-test.js
  gulpfile.js
  js/letterheads-dropdown.js
  js/row-actions.js
  manageletterheads.php
  package-lock.json
  package.json
  templates/CRM/ManageLetterheads/Form/LetterheadForm.tpl
  templates/CRM/ManageLetterheads/Page/LetterheadsListPage.tpl
  tests/js/globals/crm-config.js
  tests/js/globals/letterhead-options.js
  tests/js/helpers/block-jquery-on-ready.js
  tests/js/helpers/civicrm-api-spy.js
  tests/js/helpers/crm-confirm-spy.js
  tests/js/helpers/crm-refresh-parent-spy.js
  tests/js/karma.conf.js
  tests/js/specs/letterheads-dropdown.spec.js
  tests/js/specs/row-actions.spec.js
  xml/Menu/manageletterheads.xml
Labels: enhancement

#14 CPS-374: Release v1.0.0
  info.xml
Labels: release
